config/routes.rb
Thinkcactus::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "about/index"

  get "comments/index"

  get "work" => "work#index"

  get "posts/index"

  resources :posts do
    resources :comments
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "posts#index"

  # See how all your routes lay out with "rake routes"
  get '/about', to: 'about#index'

  get '/feed', to: 'posts#feed', as: :feed, defaults: { format: 'atom' }
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, :presence => true,
            :length => { :minimum => 5 }
  validates :author_name, :presence => true,
            :length => { :minimum => 3 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  
  belongs_to :author, :class_name => "User"
  validates :title, :presence => true,  
                    :length => { :minimum => 5 } 
  has_many :comments, :dependent => :destroy 
  friendly_id :title, use: :slugged
  
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
  
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'spyrosadmin' && password  == 'top@sstouthink'
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #make sure only the admin deletes comments.
  before_filter :authenticate, :only => :destroy

  def index
    @comments = Comment.all
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # make sure only the admin has writing and editing privileges
  before_filter :authenticate, :except => [:index, :show, :feed]

  def index
    @posts = Post.all.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  def show
    @post = Post.friendly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.friendly.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  # RSS feed
  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = "Thinkcactus | Code & Randomness"

    # retrieve the posts
    @posts = Post.order("updated_at desc")

    # feed's update timestamp
    @updated = @posts.first.updated_at unless @posts.empty?

    @description = "A blog about coding, design, music and other random thoughts. Curated by Spyros Livathinos."

    respond_to do |format|
      format.atom { render :layout => false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/admin_users_helper.rb
module Admin::AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/about/index.html.erb
<article class="post">
  <div class="about">
	  <h2>About Me</h2>
	  
	  <img src="/images/avatar_bw.jpg" title="My Profile pic" />
	  <p>Hello, my name is Spyros Livathinos. I'm a Web Engineer based in Patras, Greece. I currently work at the Computer Technology Institute of Patras, where I keep myself busy with code on a daily basis, filling roles in developing and maintaining the web stack of various projects. I hold a BS degree in Computer Engineering from the University of Patras and am currently studying for an MSc degree in Computer Science.</p>
	  <p>I have always been passionate about the web, loving the logic and challenges of backend and database engineering, deployment automation and server setup while keeping a keen eye on the details of the frontend user experience and overall design of applications. Lately my main focus has been developing web applications using Java and Ruby on Rails.</p>
	  <p>During my off hours I usually experiment with various new web technologies or check out new languages. I also am a proud <a href="https://mozillians.org/en-US/" title="My Mozilla Contributor profile">Mozillian</a> and contribute to the Firefox Developer Tools.</p>
	  <p>In no particular order, here is a brief list of my skills: Java, PHP, Ruby on Rails, MySQL, Oracle ORDBMS, Git, Mercurial, JavaScript, jQuery, HTML, CSS, Android SDK, Adobe Photoshop, Adobe Illustrator.</p>
	  <p>For more information about me, you can always have a look at my (currently desperate for an update!) <a href="/resume.pdf" title="My Resume">resume</a>. Feel free to drop me a line at livathinos.spyros[at]gmail[dot]com or follow me on <a href="https://twitter.com/spyrosl">Twitter</a>.</p>
	  
	</div>
</article>

app/views/comments/_comment.html.erb
<li class="top-space bottom-space">
	<% if comment.author_url != '' %>
	  <a href="<%= comment.author_url %>">
		  <%= comment.author_name %>
	  </a>
	<% else %>
	  <strong><%= comment.author_name %></strong>
	<% end %>
	<span class="normal-type-small">Posted <%= comment.created_at.strftime("%b %d %Y") %></p>
	<p class="normal-type"><%= comment.body %></p>
</li>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

	<div class="field">
		<%= f.text_area :body, :required => true %>
	</div><!--end of .field-->

	<div class="field">
		<%= f.label 'Your name' %>
		<%= f.text_field :author_name, :required => true %>
	</div><!--end of .field-->
	
	<div class="field">
		<%= f.label 'Website or Email' %>
		<%= f.text_field :author_url %>
	</div><!--end of .field-->
	
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div{ :title => key.to_s.humanize, :class => key }
      %p= value

app/views/layouts/_footer.html.haml
#footer
  #footer-inner
    %p.copyright © #{Date.today.year} Spyros Livathinos
  / end of #footer-inner
/ end of #footer

app/views/layouts/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/
  
  -#
    Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess
  %meta{ :content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible" }/
  %title 
    = (yield(:title) + " | " unless yield(:title).blank?).to_s + "Thinkcactus"
  %meta{ :content => "A blog about coding, design, music and other random thoughts. Curated by Spyros Livathinos.", :name => "description" }/
  %meta{ :content => "Spyros Livathinos", :name => "author" }/
  
  = auto_discovery_link_tag :atom, "/feed"
  = auto_discovery_link_tag :rss, "/feed.rss"
  
  -# Mobile viewport optimized: j.mp/bplateviewport
  %meta{ :content => "width=device-width, initial-scale=1.0", :name => "viewport" }/
    
  = csrf_meta_tag
  
  = render :partial => 'layouts/stylesheets'
  
  -# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects
  = javascript_include_tag 'modernizr.min'

app/views/layouts/_header.html.haml
%h1 Header

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag 'application', 'jquery.min', 'prettify', 'functions' %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19953990-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all', :cache => 'cache/all'

= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic,700italic', :media => 'all'
= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Quando', :media => 'all'
-# Uncomment if you are specifically targeting less enabled mobile browsers
-#= stylesheet_link_tag 'handheld', :media => 'handheld'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
= render :partial => 'layouts/head'
%body#home{ :lang => 'en', :class => "#{controller.controller_name}" }
  #header
    #header-inner
      %a{:href => "/"}
        #circle
          %img#logo{:alt => "ThinkCactus | Code & Randomness", :src => "/images/logo.png"}/
      %h1.header-label 
        spyros livathinos
        %span code & randomness
      %ul.nav
        %li
          %a.link-one{:href => "/about"} about
        %li
          %a.link-two{:href => "/work"} projects
        %li
          %a.link-three{:href => "http://twitter.com/spyrosl" } twitter
        %li
          %a.link-four{:href => "http://github.com/livathinos" } github
        %li
          %a.link-five{:href => "http://feeds.feedburner.com/thinkcactus"} feed
    / end of #header-inner
  / end of #header
  #wrapper
    #content
      = yield
    / end of #content
    .clear
  / end of #wrapper
  = render :partial => 'layouts/footer'
  = render :partial => 'layouts/javascripts'

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <div class="sep">
    <img class="bubble" src="images/thought_bubble.png" alt="" />
    <p class="date-type"><%= post.created_at.strftime(" %b %d %Y") %></p>
    <a class="tweetlink" href='http://twitter.com/?status="<%= post.title %>" by @spyrosl: <%= "http://#{request.host+ url_for(post)}" %>'>Tweet this</a>
  </div>
  <div class="nonsep">
	  <h2><%= link_to post.title, post %></h2>
    <ul class="meta-tags">
      <li>#<%= post.tag_one %>,</li>
      <li>#<%= post.tag_two %> <span>‹</span></li>
      <li>Category: <%= post.category %> <span>‹</span></li>
      <li><%= link_to "Permalink", post %> <span> →</span></li>
    </ul>
    <% if post_counter==0 %>
	    <%= post.body.html_safe %>
	  <% else %>
	    <%= truncate(post.body, :length => 500, :separator => "...").html_safe %>
	  <% end %>
	</div>
	
	<div class="bottom-sep">
	  <p class="date-type"><%= post.created_at.strftime(" %b %d %Y") %></p>
	  <%= link_to "Permalink", post %> <span> →</span>
	</div>
</article>

<hr>

app/views/posts/_postindex.html.erb
<div class="post">
	<p class="korny-type"><%= postindex.title %></p>
	<img class="bubble" src="images/thought_bubble.png" alt="" />
	<p class="date-type"><%= postindex.created_at.strftime(" %b %d %Y") %></p>
	
	<%= link_to "Full post &amp; comments", postindex, :class => "wholelink" %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="upper-container">
	<%= render :partial => "post", :collection => @posts %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<% link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% title @post.title %>
<div id="upper-container">	
	<article class="post">
	  <div class="sep">
      <img class="bubble" src="../images/thought_bubble.png" alt="" />
      <p class="date-type"><%= @post.created_at.strftime(" %b %d %Y") %></p>
      <a class="tweetlink" href='http://twitter.com/?status="<%= @post.title %>" by @spyrosl: <%= "http://#{request.host+request.fullpath}" %>'>Tweet this</a>
    </div>
    <div class="nonsep">
	    <h2><%= @post.title %></h2>
      <ul class="meta-tags">
        <li>#<%= @post.tag_one %>,</li>
        <li>#<%= @post.tag_two %><span>‹</span></li>
        <li>Category: <%= @post.category %><span>‹</span></li>
      </ul>
	    <%= @post.body.html_safe %>
	  </div>
	</article><!--end of .post-->
</div><!--end of #upper-container-->

app/views/work/index.html.haml
= title "Work and Side Projects"
#left-floater
  .blue-tag.rotate.shadow
    %p WORK
  #center-container
    #recone
      %a.next{:href => "#"} Next
      %a.previous{:href => "#"} Previous
      %ul.slider
        %li.excItem
          %h2.korny-type-small Excellence Initiative
          .snapshot-wrapper
            %img.snapshot{:alt => "Excellence Initiative", :src => "images/excellence_snap.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            A web site developed for the first stage of a big project for the Greek National Ministry of
            Education concerning the promotion of Excellence in Universities. The site acts as a promotional hub for the project and allows users
            to submit their proposals for Excellence from their respective departments, that will later on be evaluated by the Ministry and
            possibly picked for an annual Academic Excellence Convention in Greece.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML5/CSS/JavaScript
            %li AJAX
            %li CMS Integration
          %ul.technos-ext.normal-type
            %li Backend development
            %li Member management
            %li Performance optimization
            %li Server configuration & administration
          %a.visit-link{:href => "http://excellence.minedu.gov.gr/"} Visit the project
        %li.tsItem
          %h2.korny-type-small Tech Support Portal
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_ts.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            A web portal - online library dedicated to technical support documentation,
            how-tos and guides for Computer Lab administrators in Greek High and Elementary Schools. This web platform is part
            of the Greek School Network initiative and had to be designed and developed from the ground up. The CMS used is
            Joomla, with heavy customization to meet the project's needs.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS/JavaScript
            %li AJAX
            %li Template & Logo design
            %li Joomla CMS Integration
          %ul.technos-ext.normal-type
            %li CAS Login system
            %li Member management
            %li Performance optimization
            %li Server configuration & administration
          %a.visit-link{:href => "http://ts.sch.gr"} Visit the project
        %li.ditysItem
          %h2.korny-type-small Ditys
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_ditys.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            An informational web portal dedicated to the Infrastructure and Technical Support Sector of the
            Research Academic Computer Technology Insitute. This platform was built ontop of the Joomla CMS with modifications
            to support the Single Sign On login system via LDAP authentication as well as the member management system. The platform
            was developed for intranet-only use.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS/JavaScript
            %li AJAX
            %li Template & Logo design
            %li CMS integration
          %ul.technos-ext.normal-type
            %li Single Sign On Login system
            %li Member management
            %li Server administration
        %li.khomeItem
          %h2.korny-type-small Khome Productions Portfolio
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_khomep2.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            A photography portfolio that was developed for a client, Khome productions. The theme as
            requested was "simplicity" and the template was designed with that in mind. The site was integrated into Wordpress
            for ease of use by the client, and supports news and gallery management with a custom built gallery script running
            on the frontend.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS/JavaScript
            %li AJAX
            %li Template & Logo design
            %li Wordpress integration & customization
          %ul.technos-ext.normal-type
          %a.visit-link{:href => "http://khomeproductions.gr"} Visit the project
        %li.shopItem
          %h2.korny-type-small Khome productions E-shop
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_khomes.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            In accordance with their portfolio needs, Khome productions asked us to deliver an e-shop
            solution for online web sales of their clients' photos. The implementation is based on osCommerce with (really)
            heavy customization.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS/JavaScript
            %li Template & Logo design
            %li Customized orders system
            %li osCommerce Integration
          %ul.technos-ext.normal-type
          %a.visit-link{:href => "http://shop.khomeproductions.gr"} Visit the project
        %li.carnivalItem
          %h2.korny-type-small Carnival Patra
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_carnival.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            CarnivalPatra is a web site for people coming to the city of Patras in search of attractions,
            carnival groups and other activities in the period of Greece's most famous carnival. The site was implemented on Wordpress
            with some extra customization as far as member management is concerned.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS/JavaScript
            %li AJAX
            %li Template & Logo design
            %li Wordpress integration
          %ul.technos-ext.normal-type
            %li Member management
          %a.visit-link{:href => "http://carinivalpatras.gr"} Visit the project
        %li.pavItem
          %h2.korny-type-small Pavimento
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_pavimento.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            Pavimento is one of the leading Linoleum-based floor and wall dressing companies in Greece.
            As part of their collaboration with other European companies in the field, they asked for a simple website that would
            help inform their clients about what they do and get a glimpse of their handywork.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS
            %li Javascript
          %ul.technos-ext.normal-type
          %a.visit-link{:href => "http://pavimento-art.gr"} Visit the project
    .green-tag.rotate.shadow
      %p ON THE SIDE
    #rectwo
      %a.next{:href => "#"} Next
      %a.previous{:href => "#"} Previous
      %ul.slider
        %li.issuesItem
          %h2.korny-type-small Issues Tracker
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_issues.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            A simple issue tracker which was built and used during the development of the Tech Support
            Portal. The issue tracking of CVS systems such as BitBucket or GitHub was just too complex for the needs of the
            project and the number of people involved in it (One developer and one project manager), so I developed this handy tool
            to be able to publish issues fast and easy on a single feed like web app.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li HTML/CSS
            %li AJAX
            %li Javascript
            %li UI design
          %ul.technos-ext.normal-type
          %a.visit-link{:href => "http://bitbucket.org/spyros_l/issues"} Visit the project
        %li.financoidItem
          %h2.korny-type-small Financoid Android App
          .snapshot-wrapper
            %img.snapshot{:alt => "Ditys - CTI website", :src => "images/main_snap_financoid.jpg"}/
          %h3.container-header-brief Brief description
          %p.description.normal-type
            As part of my undergraduate thesis at the Computer Engineering & Informatics Department of the
            UoP I developed an Android Application for handheld devices which simplifies the task of keeping track of ones everyday
            expenses. The app lets the user handle their monthly and total budget, create new budget categories and watch their spending
            expense patterns per month and budget category.
          %h3.container-header-tech My Involvement
          %ul.technos.normal-type
            %li Java development on the Android SDK
            %li UI design
          %a.visit-link{:href => "http://bitbucket.org/spyros_l/app.financoid"} Visit the project
  / end of #center-container